name: Package
on: push
jobs:
  package:
    runs-on: ubuntu-latest
    name: Package
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
      - run: |
          yarn install
          yarn build
      - run: rm -rf node_modules/ src/ .git/
      - uses: actions/upload-artifact@v2
        with:
          name: scroll-tracker
          path: .
